Repository charleshenriponiard/spayce_2, pull requests merged in 2020-11, with the labels that each got.

#73 Add cache policy on bundler for github actions
  .github/workflows/main.yml
  README.md
Labels: Front, refacto

#74 Canceled project status
  app/controllers/projects_controller.rb
  app/policies/project_policy.rb
  app/views/projects/show.html.erb
  config/routes.rb
  spec/factories/user_factory.rb
  spec/policies/project_policy_spec.rb
Labels: Front, bug, refacto

#76 pagy ok
  Gemfile
  Gemfile.lock
  app/controllers/projects_controller.rb
  app/helpers/application_helper.rb
  app/views/projects/index.html.erb
  config/initializers/pagy.rb
Labels: Config, Front, enhancement

#75 Send page
  app/assets/stylesheets/components/_bill.scss
  app/controllers/projects_controller.rb
  app/helpers/confirmation_card_helper.rb
  app/javascript/components/clipboard.js
  app/javascript/controllers/bill_controller.js
  app/javascript/packs/application.js
  app/mailers/client_mailer.rb
  app/policies/project_policy.rb
  app/views/client_mailer/transfert_project_to_client.html.erb
  app/views/projects/_bill.html.erb
  app/views/projects/_form.html.erb
  app/views/projects/confirmation.html.erb
  app/views/projects/new.html.erb
  config/routes.rb
  db/migrate/20201112165413_c_hange_default_valu_to_project_status.rb
  db/schema.rb
  test/mailers/client_transfert_mailer_test.rb
  test/mailers/previews/client_transfert_mailer_preview.rb
Labels: Front, enhancement, refacto

#78 skip_before_action Clients::Projects#show
  app/controllers/clients/projects_controller.rb
Labels: refacto

#79 Client pundit
  app/controllers/clients/projects_controller.rb
  app/policies/clients/project_policy.rb
  test/policies/clients/project_policy_test.rb
Labels: bug, enhancement

#82 sent_email, refacto layout email
  app/mailers/application_mailer.rb
  app/views/client_mailer/transfert_project_to_client.html.erb
  config/locales/en.yml
  config/locales/fr.yml
Labels: Front, refacto

#91 Action mailer
  app/policies/project_policy.rb
  app/views/client_mailer/payment_validation.html.erb
  app/views/client_mailer/project_canceled.html.erb
  app/views/client_mailer/transfert_project_to_client.html.erb
  app/views/user_mailer/freelance_project_canceled.html.erb
  app/views/user_mailer/kyc_validated.html.erb
  config/locales/fr.yml
  db/schema.rb
  spec/policies/project_policy_spec.rb
Labels: bug, enhancement, refacto

#93 new mail after accepted payment for the freelance
  app/mailers/user_mailer.rb
  app/models/project.rb
  app/views/user_mailer/accepted_payment.html.erb
  config/locales/en.yml
  config/locales/fr.yml
Labels: Front

#94 refacto order in project_policy scope
  app/policies/project_policy.rb
  app/views/projects/index.html.erb
Labels: refacto

#96 hange format date with i18n, update projects#show
  app/controllers/projects_controller.rb
  app/views/client_mailer/payment_validation.html.erb
  app/views/client_mailer/project_canceled.html.erb
  app/views/client_mailer/transfert_project_to_client.html.erb
  app/views/projects/show.html.erb
  app/views/user_mailer/freelance_project_canceled.html.erb
  config/locales/en.yml
  config/locales/fr.yml
Labels: refacto

#99 add taxes line
  app/views/projects/show.html.erb
  config/locales/en.yml
  config/locales/fr.yml
Labels: refacto

#109 add if in update project job for create invoice
  app/jobs/update_project_job.rb
  app/services/stripe/payment_intent_event_handler.rb
  db/schema.rb
Labels: refacto

#111 Rspec
  app/controllers/projects_controller.rb
  app/mailers/client_mailer.rb
  app/mailers/user_mailer.rb
  app/services/stripe/account_updated_event_handler.rb
  app/views/client_mailer/project_canceled.html.erb
  app/views/client_mailer/transfert_project_to_client.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  spec/client_mailer/client_expired_spec.rb
  spec/client_mailer/client_reminder_spec.rb
  spec/client_mailer/payment_validation_spec.rb
  spec/client_mailer/project_canceled_spec.rb
  spec/client_mailer/transfert_project_to_client_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/user_mailers/accepted_payment_spec.rb
  spec/user_mailers/freelance_project_canceled_spec.rb
  spec/user_mailers/kyc_validated_spec.rb
  spec/user_mailers/user_expired_spec.rb
  spec/user_mailers/user_reminder_spec.rb
Labels: Test, bug, enhancement

#114 Project policy spec
  spec/policies/clients/project_policy_spec.rb
Labels: Test

#113 test bucket
  app/entities/multi_file_zipper_download.rb
  app/helpers/document_previews_helper.rb
  spec/entities/multi_file_zipper_download_spec.rb
  spec/fixtures/test.png
  spec/fixtures/test_file.rb
  spec/rails_helper.rb
Labels: Test

#115 update project job spec ok
  spec/jobs/update_project_job_spec.rb
Labels: Test

#116 invoices_controller_spec, invoice_policy_spec
  spec/controllers/invoices_controller_spec.rb
  spec/policies/invoice_policy_spec.rb
Labels: Test

#117 clients_projects_controller_spec ok
  spec/controllers/clients/projects_controller_spec.rb
Labels: Test
