Repository charleshenriponiard/spayce_2, pull requests merged in 2020-09, with the labels that each got.

#1 add heroku task in procfile
  Procfile
Labels: documentation

#2 change procfile, add heroku-prod logs in overmind
  Procfile
Labels: documentation

#3 Test environement
  .gitignore
  .rspec
  Gemfile
  Gemfile.lock
  spec/factories/user_factory.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/factory_bot.rb
  test/application_system_test_case.rb
  test/channels/application_cable/connection_test.rb
  test/controllers/.keep
  test/fixtures/.keep
  test/fixtures/files/.keep
  test/helpers/.keep
  test/integration/.keep
  test/mailers/.keep
  test/models/.keep
  test/models/user_test.rb
  test/system/.keep
  test/test_helper.rb
Labels: documentation

#13 Sign in
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/config/_bootstrap_variables.scss
  app/assets/stylesheets/config/_colors.scss
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_links.html.erb
Labels: Front

#14 refacto front sign in
  app/assets/stylesheets/components/_card.scss
  app/views/devise/sessions/new.html.erb
  config/initializers/simple_form_bootstrap.rb
Labels: Front

#15 Update devise form with new style, add errors on form
  app/assets/stylesheets/components/_alert.scss
  app/assets/stylesheets/components/_card.scss
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
Labels: Front

#16 Redirect sign up
  app/controllers/registrations_controller.rb
  app/controllers/stripes_controller.rb
  app/views/stripes/sign_up.html.erb
  config/routes.rb
Labels: new feature

#17 change registrations#edit, can change info user withou password
  app/controllers/registrations_controller.rb
  app/helpers/application_helper.rb
  app/views/devise/registrations/edit.html.erb
Labels: Front, new feature

#18 update devise
  app/assets/stylesheets/components/_card.scss
  app/controllers/application_controller.rb
  app/mailers/application_mailer.rb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  config/initializers/devise.rb
Labels: Front, bug

#19 test async mail devise ok
  Gemfile
  Gemfile.lock
  app/models/user.rb
  config/environments/development.rb
  config/initializers/devise_async.rb
Labels: bug, new feature

#20 change config.action_mailer.default_url_options production.rb
  config/environments/production.rb
Labels: Config

#21 .delivery_method = smtp
  config/environments/production.rb
Labels: Config

#22 change style reset_password email
  app/views/devise/mailer/reset_password_instructions.html.erb
Labels: Front

#23 Email validation
  app/mailers/devise_custom_mailer.rb
  app/models/user.rb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/layouts/mailer.html.erb
  config/initializers/devise.rb
  db/migrate/20200916073427_add_confirmable_to_devise.rb
  db/schema.rb
  spec/jobs/create_company_job_spec.rb
Labels: Config, Front

#24 .skip_confirmation! in seed, clear Mailer queue! in seed
  db/seeds.rb
Labels: bug, refacto

#26 Refacto
  app/controllers/stripes_controller.rb
  app/controllers/users/confirmations_controller.rb
  app/controllers/users/omniauth_callbacks_controller.rb
  app/controllers/users/passwords_controller.rb
  app/controllers/users/registrations_controller.rb
  app/controllers/users/sessions_controller.rb
  app/controllers/users/unlocks_controller.rb
  app/models/stripe/express.rb
  app/models/user.rb
  app/views/devise/registrations/edit.html.erb
  app/views/stripes/sign_up.html.erb
  app/views/users/resgistrations/edit.html.erb
  app/views/users/resgistrations/new.html.erb
  config/routes.rb
Labels: refacto

#27 refacto registrations#edit
  app/models/stripe/express.rb
  app/models/user.rb
  app/views/devise/registrations/edit.html.erb
Labels: refacto

#30 add new queue stripe
  app/jobs/update_user_job.rb
  config/sidekiq.yml
Labels: Config

#33 Rspec stripe
  Gemfile
  Gemfile.lock
  app/controllers/stripes_controller.rb
  app/models/stripe/express.rb
  config/environments/test.rb
  config/initializers/stripe_events.rb
  dump.rdb
  spec/cassettes/stripe_account_unboarded.yml
  spec/cassettes/stripe_onboarding.yml
  spec/cassettes/stripe_sign_up.yml
  spec/cassettes/test.yml
  spec/controllers/stripes_controller_spec.rb
  spec/factories/user_factory.rb
  spec/jobs/create_company_job_spec.rb
  spec/models/stripe_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/controller_macros.rb
  spec/support/devise.rb
  spec/support/vcr.rb
  test/policies/registration_steps_policy_test.rb
  test/policies/stripes_policy_test.rb
  test/policies/users_policy_test.rb
Labels: Config, bug, refacto

#35 add test to Stripe::AccountUpdatedEventHandler#call
  spec/services/account_update_handler_spec.rb
Labels: refacto

#36 add tests to resgistrations_controller.rb
  spec/controllers/registrations_controller_spec.rb
Labels: refacto

#37 Project
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/projects_controller.rb
  app/models/project.rb
  app/models/user.rb
  app/policies/project_policy.rb
  app/views/projects/new.html.erb
  config/routes.rb
  db/migrate/20200924133901_create_projects.rb
  db/schema.rb
  spec/controllers/projects_controller_spec.rb
  spec/factories/project_factory.rb
  spec/factories/user_factory.rb
  test/policies/project_policy_test.rb
Labels: Test, enhancement

#38 User seed
  app/views/projects/new.html.erb
  db/seeds.rb
  spec/factories/project_factory.rb
Labels: Test, refacto

#39 Add aws S3 and document uploading
  Gemfile
  Gemfile.lock
  app/controllers/projects_controller.rb
  app/models/project.rb
  app/views/projects/new.html.erb
  config/environments/production.rb
  config/storage.yml
  db/migrate/20200925095429_create_active_storage_tables.active_storage.rb
  db/schema.rb
Labels: Config

#42 spec on resgistration steps controller action show and update
  spec/cassettes/stripe_sign_up_registration_steps.yml
  spec/cassettes/test.yml
  spec/controllers/registration_steps_controller_spec.rb
Labels: Test, enhancement

#43 Watermark
  Gemfile
  Gemfile.lock
  app/assets/images/watermark.png
  app/models/project.rb
  app/views/pages/home.html.erb
  config/initializers/active_storage_previewers.rb
  lib/assets/images/watermark.png
Labels: Config, new feature

#45 upate documents without remove older
  app/views/projects/show.html.erb
  config/application.rb
Labels: bug, refacto

#46 Remove documents
  app/controllers/projects_controller.rb
  app/policies/project_policy.rb
  app/views/projects/show.html.erb
  config/routes.rb
Labels: enhancement

#47 create _preview
  app/views/projects/_preview.html.erb
  app/views/projects/show.html.erb
Labels: enhancement

#48 Zip
  Gemfile
  Gemfile.lock
  app/controllers/projects_controller.rb
  app/entities/multi_file_zipper_download.rb
  app/services/s3_service.rb
  config/storage.yml
Labels: Config, enhancement, refacto

#49 TASK-6 create zip_documents_job
  app/controllers/projects_controller.rb
  app/jobs/zip_documents_job.rb
  app/views/projects/show.html.erb
  config/sidekiq.yml
  db/migrate/20200930133723_add_default_value_toproject.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/project_factory.rb
Labels: enhancement, refacto

#50 TASK-8
  app/entities/multi_file_zipper_download.rb
  app/jobs/zip_documents_job.rb
Labels: refacto
